version: '3.9'

services:
  rails-app:
    build: 
      context: ../
      dockerfile: .docker/application/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../src:/usr/src/app
    depends_on:
      - rails-database

  rails-database:
    container_name: bas-mysql
    build: 
      context: ../
      dockerfile: .docker/database/Dockerfile
    ports:
      - "13306:3306"
    volumes:
      # MySQLデータ
      - ./database/data:/var/lib/mysql
      # 初期化用のSQL配置
      - ./database/sql:/docker-entrypoint-initdb.d
    tty: true
    restart: always
  